name: flutter_redurx
version: 1.1.1
description: Flutter bindings for ReduRx (A thin layer of a Redux-based state manager on top of RxDart).
author: leocavalcante <lc@leocavalcante.com>
homepage: https://github.com/leocavalcante/ReduRx

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  redurx: ^1.1.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
